source 'https://rubygems.org'

gem 'sinatra'
gem 'slim'
gem 'sqlite3'
gem 'rerun'
gem 'byebug'
gem 'bcrypt'
gem 'rack-flash3'
gem 'capybara'
gem 'rspec'
gem 'selenium-webdriver'
gem 'racksh'
gem 'wdm'